dataset_path: flaviagiammarino/vqa-rad
dataset_kwargs:
  token: true
task: "vqa_rad"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.vqa_rad_doc_to_visual
doc_to_text: !function utils.vqa_rad_doc_to_text
doc_to_target: "answer"
process_results: !function utils.vqa_rad_process_results

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with a single word or short phrase."

generation_kwargs:
  max_new_tokens: 2048
  temperature: 0
  do_sample: false

metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true

metadata:
  - version: 0.0
